- package.json
- src/services/FilesystemKeystoreService.ts
- src/services/OpenidForPresentationReceivingService.ts
- src/services/interfaces.ts
- yarn.lock
This update removes checks of the "nbf" JWT field as it caused problems when the client which produces JWTs lacks clock synchronization
> updated ssi sdk version

- src/app.ts
- src/openid4vci/Proof/verifyProof.ts
- src/services/OpenidForPresentationReceivingService.ts
- src/verifier/verifierRouter.ts
Added clock tolerance on jwt verification functions. This addresses the [nbf removal open issue](https://github.com/wwWallet/wallet-ecosystem/issues/44)
> Clock tolerance

- public/styles/styles.css
- views/issuer/consent.pug
This PR updates the modal's styling!
> Improved Modal Styling

- src/app.ts
- src/authorization/consentPage.ts
- src/entities/AuthorizationServerState.entity.ts
- src/services/OpenidForCredentialIssuingAuthorizationServerService.ts
- src/services/interfaces.ts
Fixes https://github.com/wwWallet/wallet-enterprise/issues/27
> Issuer state support + exposed endpoint to bind issuer state with data

- public/js/consent.js
- public/styles/consent.css
- views/issuer/consent.pug
This PR streamlines the process of selecting credentials by eliminating the "Select" button. It will display credential details with a button, and incorporate check/uncheck icons for an intuitive selection experience.
> Simplify Credentials Selection

- public/js/consent.js
- views/issuer/consent.pug
This PR is a continuation of PR #35 and addresses an issue found in the authorization code flow. Specifically, it resolves a problem encountered when attempting to get credentials.
> Fix for Authorization Code Flow Issue in Get Credentials

- views/footer.pug
The footer will now dynamically display the current year using JavaScript.
> Update Footer to Dynamically Display Current Year

- src/app.ts
> used max age for expiring a cookie

- public/js/presentation-request.js
- views/verifier/success.pug
> Avoid redundant fetches, remove deprecated code

- src/lib/generateDataUriFromSvg.ts
Related with:
- https://github.com/wwWallet/wallet-ecosystem/pull/105
- https://github.com/wwWallet/wallet-frontend/pull/433
> Update generateDataUriFromSvg base on svg_id

- views/verifier/selectable_presentation.pug
Fixes https://github.com/wwWallet/wallet-ecosystem/issues/101
> Disable vc type selection to avoid getting VCs with missing attributes

- src/services/ExpressAppService.ts
- src/services/OpenidForCredentialIssuingAuthorizationServerService.ts
Support batch issuance by accepting multiple proofs to bind credentials with different keypairs
> Batch Issuance

- public/js/auth-method-selection.js
- public/styles/scan-qr-verifier.css
- src/authentication/authenticationComponentTemplates/GenericAuthenticationMethodSelectionComponent.ts
- src/authentication/authenticationComponentTemplates/GenericVIDAuthenticationComponent.ts
- src/configuration/locale.ts
- views/issuer/auth-method-selection.pug
- views/issuer/vid-auth-component.pug
Abstract the authentication method selection component into a generic authentication component to remove the requirement of including it into the configuration every time in the authentication chain from scratch.
The only thing required is to add the generic authentication method selection component on the authentication chain by providing the available authentication methods associated with a user-friendly description.
Also this PR introduces a loader with a countdown for the VID authentication component
> Generic authentication method selection

- src/services/ExpressAppService.ts
Closes https://github.com/wwWallet/wallet-enterprise/issues/101
> Expose SDJWT VC issuer metadata

- src/authentication/authenticationComponentTemplates/GenericVIDAuthenticationComponent.ts
- views/issuer/vid-auth-component.pug
> Fix unresponsive cancel button during PID-based authentication

- src/app.ts
- views/index.pug
Related with https://github.com/wwWallet/wallet-ecosystem/pull/160
> Display sd-jwt vc type metadata on each credential type if exists

- public/js/configurable-presentation.js
> Add missing input descriptor ids in configurable pres. definitions

- src/app.ts
- views/index.pug
Reverts wwWallet/wallet-enterprise#126
> Revert "Display sd-jwt vc type metadata on each credential type if exists"

- public/styles/edit-presentation-definition.css
- public/styles/styles.css
- src/verifier/verifierRouter.ts
- views/verifier/edit_presentation_definition.pug
Added basic schema validation and syntax highlighting
> Syntax-aware definition editor for custom presentations

- public/js/configurable-presentation.js
- public/styles/configurable-presentation.css
- views/verifier/configurable_presentation.pug
Quality of life upgrade for the attribute selection form.
> Added select all and select none controls on attributes form

- public/js/configurable-presentation.js
- public/styles/configurable-presentation.css
- src/verifier/verifierRouter.ts
- views/verifier/configurable_presentation.pug
> Added selector to change between vc+sd-jwt and dc+sd-jwt

- src/configuration/issuerSigner.ts
- src/services/OpenidForPresentationReceivingService.ts
Related PRs:
- https://github.com/wwWallet/wallet-ecosystem/pull/220
> Fix: remove root ca cert from x5c header

- src/configuration/issuerSigner.ts
- src/services/ExpressAppService.ts
Fix for #178.
* Created a helper function to convert disclosure frame structure to the newest format required by openwallet-foundation/sd-jwt-js
* Utilized the libraries data structures instead of manually signing the credentials, passing the disclosure information as a parameter
> Utilization of Disclosure Frame object during sdjwt issuance

- src/verifier/verifierRouter.ts
Related PR: https://github.com/wwWallet/wallet-common/pull/31
> Feat Verifier Callback to Await Async Credential Image URI

- src/services/OpenidForPresentationReceivingService.ts
During presentation with no claims selected, it is implied (OID4VP d.24) that all claims are requested. This PR fixes the details on the success page of such presentations where no attributes were shown even though all of them had been presented.
> Fix missing claims from successful presentation of all claims
